### ISSUE TITLE
CMake error  "Could NOT find Libobs"

### ISSUE THREAD

**Issue by IWS2000** [stream-labs/facemask-plugin#29]
Hi, I have a trouble in Cmake.
Following pictures are my environment and setup.

OBS, it works.
![obs_successful1](https://user-images.githubusercontent.com/34673758/45549552-cf57b800-b85a-11e8-90fa-bde0bf017b5c.jpg)
![obs_successful2](https://user-images.githubusercontent.com/34673758/45549554-cf57b800-b85a-11e8-9ee4-a7856fc81862.jpg)

facemask-plugin, get an error.
![plugin_error1](https://user-images.githubusercontent.com/34673758/45549704-42f9c500-b85b-11e8-9997-d2da13d944b2.jpg)
![plugin_error2](https://user-images.githubusercontent.com/34673758/45549556-cff04e80-b85a-11e8-9105-1839be86f8b6.jpg)

Am I missing something?
Thank you.

**Comment by glaba13** [comment]
Hi IWS2000,

After Generating *obs-studio*, did you build the project?
Here is the steps from obs-studio README,
The last step is important for the generation of libobs library:
> .....
> - Press 'Generate' to generate Visual Studio project files in the 'build' subdirectory.
> 
> - **Open obs-studio.sln from the 'build' subdirectory in Visual Studio** (or click the Open Project button from the cmake-gui in 3.7+), and it should run and be good to go. All required dependencies should be copied on compile and it should be a fully functional build environment. The output is built in the 'rundir/[build type]' directory of your 'build' subdirectory.

**Comment by IWS2000** [comment]
Hi @glaba13, 

Yes, I built it and it can run.
I also tried to download and build the latest version of OBS,
but still got this error in Cmake.

Thank you for your reply.

**Comment by glaba13** [comment]
Hi @IWS2000,
Thanks for your details.

Please rename the obs-studio build folder:
Instead of **obs-studio/build_64bit_2015**  to  **obs-studio/build**
It should work.
You can also rename to build64, As we read from instructions:

> Create one or more of the following subdirectories within the cloned repository for building: release, debug, and build (suffixed with or without 32/64 to specify architecture). They are excluded from the repo in .gitignore for the sake of building, so they are safe to create an use within the repository base directory.

**Comment by IWS2000** [comment]
Hi @glaba13,
Thanks for your help!

It works, I successfully configured and generated the plugin project with Cmake.
I named the folder "build_64bit_2015" in order to distinguish the build configure easily,
but I didn't expect it caused an error in Cmake.

Thank you.
