### ISSUE TITLE
How to create the masks by myself?

### ISSUE THREAD

**Issue by IWS2000** [stream-labs/facemask-plugin#31]
Hello Streamlabs,

Your facemask is very good and interesting.
I am wondering how to create some masks, such as a hat and a red nose by myself.
May you give me some information?

Thanks.

**Comment by glaba13** [comment]
Hi @IWS2000,

Unfortunately, it's not possible right now,
However, there will be more exciting and amazing masks soon.

Regards,
Guri

**Comment by IWS2000** [comment]
Hi @glaba13,

Ok, that's too bad.
I look forward to your new version of facemask. 

Thanks for your reply.
