### ISSUE TITLE
 LNK1107 invalid or corrupt file: cannot read at 0x86 

### ISSUE THREAD

**Issue by ginxxxxx** [stream-labs/facemask-plugin#93]
1>------ Build started: Project: facemask-plugin, Configuration: Release x64 ------
1>..\thirdparty\opencv\lib\Release\opencv_world400.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x86
1>Done building project "facemask-plugin.vcxproj" -- FAILED.

**Comment by r4ghu** [comment]
Hi @ginxxxxx,
Thank you for posting the issue. Can you please provide us some more information such as your system config, Visual studio version and complete BUILD log? It can help us to investigate more on this issue.

**Comment by ginxxxxx** [comment]
I resolved the issue by installing git-lfs. If it is not installed the clone will corrupt larger files.

Thank you.
