### ISSUE TITLE
How to install plugin files into slobs?

### ISSUE THREAD

**Issue by ginxxxxx** [stream-labs/facemask-plugin#96]
I cannot find the "Setting of facemask-plugin" in slobs. Face mask is listed in add filter to source and can be added but does nothing and has no "settings". 

I believe all builds successful.  I copied the plugin files into slob's plugin directory (both the dll and the data folder).  I can provide build logs if necessary.

**Comment by kamyarinfinity** [comment]
If you see no settings for facemask filter, it means you have built the facemask plugin in release mode. You have to configure CMake, and set BUILD_FOR_PUBLIC to OFF if you need the settings. But that has nothing to do with triggering the masks. If you have an issue with no masks showing up, it can have very different reasons. First thing to check is you have the alert box widget.
If that didn't work, the latest log file here should give more info on whether the plugin was loaded, and if any masks were triggered: `%APPDATA%/slobs-client\node-obs\logs`
