### ISSUE TITLE
How to make it work as default

### ISSUE THREAD

**Issue by MutanGFX** [stream-labs/facemask-plugin#97]
I didn't get it to work in the SLOBS using the donations, wondering if it's possible to just let it always on, and how to do so.
Thanks in advance.

**Comment by glaba13** [comment]
Hi @MutanGFX,

Please see the tutorial in order to use facemasks in slobs: https://streamlabs.com/face-mask-tutorial
For using it as always on, you need to build the plugin with **BUILD_FOR_PUBLIC** flag OFF and set **draw mask** option ON

**Comment by MutanGFX** [comment]
Thanks @glaba13 ,
I have 0 clues on how to build the plugin. Does it mean following every step in the Compiling part of the README except from the build OBS?
Isn't there a way you could just send me the plugin with the **BUILD_FOR_PUBLIC** flag OFF already?

**Comment by glaba13** [comment]
@MutanGFX,

A non-standard build is for development use,  the readme describes all the necessary steps.
In your case, I would suggest following the [tutorial](https://streamlabs.com/face-mask-tutorial) to use facemasks and you can contact the support team for the further questions of standard usage/setup.

**Comment by MutanGFX** [comment]
@glaba13 ,
sure, could you at least tell me if I need to build OBS or not?

**Comment by glaba13** [comment]
@MutanGFX 
Yes you need:

> [**obs-studio**](https://github.com/stream-labs/obs-studio)
>
> Do not forget the submodules:
> 
> `git clone --recursive https://github.com/stream-labs/obs-studio.git`
>
> **Build obs-studio**
> 
> Follow the build instructions here:
> 
> [build instructions](https://github.com/obsproject/obs-studio/wiki/Install-Instructions#windows-build-directions)
> 
> Note: You do not need to install Qt5 as a dependency, just make sure ENABLE_UI in CMake GUI is not checked before Configure/Generate. You can also handle this by setting ENABLE_UI to OFF in CMakeLists in the obs-studio folder.

**Comment by MutanGFX** [comment]
That's happening @glaba13 
![image](https://user-images.githubusercontent.com/20274092/51283413-dccaad80-19c6-11e9-98c7-a4cef89e3225.png)

**Comment by MutanGFX** [comment]
![image](https://user-images.githubusercontent.com/20274092/51287627-2de29d80-19d7-11e9-8ef8-4d731862511e.png)

Stuck here now @glaba13

**Comment by MutanGFX** [comment]
Tried again and now the same error PATH_DLIB is invalid during the obs build. Idk what to do anymore

**Comment by r4ghu** [comment]
This is happening because dlib submodule is not downloaded in your repository. If you are using git bash, please navigate to `facemask-plugin/` directory and type the following command:

```
git submodule update --init --recursive
```

This command should install `dlib` and `freetype` submodules that are required by the plugin.

**Comment by MutanGFX** [comment]
Thanks @r4ghu.
![image](https://user-images.githubusercontent.com/20274092/51302441-2809ae00-1a11-11e9-8cf9-4c8e5cacd811.png)
I don't know if that error is common
![image](https://user-images.githubusercontent.com/20274092/51302468-38218d80-1a11-11e9-97c9-765bdd8c303e.png)
That's all in the folder
How exatcly do I have to use that command? Just start a Git Bash in the folder? Tried it and didn't really work.

**Comment by MutanGFX** [comment]
![image](https://user-images.githubusercontent.com/20274092/51303137-35279c80-1a13-11e9-9a03-6b3c85ec3422.png)
Did a git submodule add to add the two submodules, still the same error
